import entityData from "__ENTITY_DATA_IMPORT__";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

type EntityRecord = {
  id: string;
  name: string;
  slug: string;
  source: "csv" | "seed";
  seedKeyword?: string;
  metadata?: {
    title?: string;
    description?: string;
    tags?: string[];
  };
};

type PageProps = {
  params: Promise<{
    entity: string;
  }>;
};

const entities = entityData as EntityRecord[];

function getEntity(slug: string): EntityRecord | undefined {
  return entities.find((entity) => entity.slug === slug);
}

function getEntityOrThrow(slug: string): EntityRecord {
  const entity = getEntity(slug);

  if (!entity) {
    notFound();
  }

  return entity;
}

export async function generateStaticParams(): Promise<Array<{ entity: string }>> {
  return entities.map((entity) => ({ entity: entity.slug }));
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { entity: slug } = await params;
  const entity = getEntity(slug);

  if (!entity) {
    return {};
  }

  return {
    title: entity.metadata?.title ?? entity.name,
    description: entity.metadata?.description ?? `Explore ${entity.name}.`,
    alternates: {
      canonical: `/${entity.slug}`,
    },
  };
}

export default async function EntityPage({ params }: PageProps) {
  const { entity: slug } = await params;
  const entity = getEntityOrThrow(slug);

  const related = entities.filter((item) => item.slug !== entity.slug).slice(0, 5);

  return (
    <main className="mx-auto flex min-h-screen max-w-4xl flex-col gap-10 px-6 py-16">
      <section className="space-y-4">
        <p className="text-sm uppercase tracking-[0.2em] text-neutral-500">Sophon pSEO scaffold</p>
        <h1 className="text-4xl font-semibold tracking-tight text-neutral-950">
          {entity.metadata?.title ?? entity.name}
        </h1>
        <p className="max-w-2xl text-base leading-7 text-neutral-700">
          {entity.metadata?.description ?? `Programmatic SEO landing page scaffold for ${entity.name}.`}
        </p>
      </section>

      <section className="grid gap-6 md:grid-cols-[2fr_1fr]">
        <article className="space-y-6 rounded-3xl border border-neutral-200 p-8">
          <div className="space-y-3">
            <h2 className="text-2xl font-medium text-neutral-950">Overview</h2>
            <p className="text-neutral-700">
              This route was generated by Sophon from a dataset of __ENTITY_COUNT__ entities.
            </p>
            <p className="text-neutral-700">
              TODO: Replace this scaffold copy with AI-generated content blocks, structured comparisons,
              FAQs, and conversion-focused sections.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-2xl font-medium text-neutral-950">Suggested data model</h2>
            <p className="text-neutral-700">
              Keep canonical entity data in `data/entities.json` or migrate it into your preferred CMS,
              warehouse, or enrichment pipeline.
            </p>
            <p className="text-neutral-700">
              TODO: Add niche-specific components, trust signals, case studies, pricing blocks, or feature
              comparisons here.
            </p>
          </div>
        </article>

        <aside className="space-y-6 rounded-3xl bg-neutral-50 p-8">
          <div className="space-y-3">
            <h2 className="text-lg font-medium text-neutral-950">Entity metadata</h2>
            <dl className="space-y-2 text-sm text-neutral-700">
              <div>
                <dt className="font-medium text-neutral-900">Slug</dt>
                <dd>{entity.slug}</dd>
              </div>
              <div>
                <dt className="font-medium text-neutral-900">Source</dt>
                <dd>{entity.source}</dd>
              </div>
              {entity.seedKeyword ? (
                <div>
                  <dt className="font-medium text-neutral-900">Seed keyword</dt>
                  <dd>{entity.seedKeyword}</dd>
                </div>
              ) : null}
            </dl>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-medium text-neutral-950">Related pages</h2>
            <ul className="space-y-2 text-sm text-neutral-700">
              {related.map((item) => (
                <li key={item.slug}>
                  <Link className="underline decoration-neutral-300 underline-offset-4" href={`/${item.slug}`}>
                    {item.name}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </aside>
      </section>
    </main>
  );
}